#服务端口号
server:
  port: 8080

apis:
  dev-url: http://localhost:8080
  url: http://110.40.253.237:8080


file-upload:
  image:
    winUrl: "c:/subject"
    linuxUrl: "/usr/subject"


spring:
  servlet:
    multipart:
      max-request-size: 200MB
      max-file-size: 100MB
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/,file:${file-upload.image.winUrl},file:${file-upload.image.linuxUrl}
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/subjectcompetition?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

#jpa配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
